const express = require('express');
const router = express.Router()
const clientController = require('../controllers/clientController')

router.route('/')
    .get(clientController.getAllClientsHandler)
    .post(clientController.createNewClientHandler)
    .put(clientController.updateClientHandler)
router.route('/search')
    .get(clientController.handleSearchClients)
router.route('/verify/:id')
    .put(clientController.handleVerifyClient)
router.route('/unverify/:id')
    .put(clientController.handleUnverifyClient)
router.route('/onmain/:id')
    .put(clientController.handleOnMaintenanceAlert)
router.route('/offmain/:id')
    .put(clientController.handleOffMaintenanceAlert)
router.route('/onsec/:id')
    .put(clientController.handleOnSecurityAlert)
router.route('/offsec/:id')
    .put(clientController.handleOffSecurityAlert)
router.route('/onplan/:id')
    .put(clientController.handleOnPlanUpgradeAlert)
router.route('/offplan/:id')
    .put(clientController.handleOffPlanUpgradeAlert)
router.route('/transfer/:id')
    .post(clientController.handleTransferFunds)
router.route('/withdrawal-limit/:id')
    .put(clientController.handleSetWithdrawalLimit)
router.route('/mining/machines/:id')
    .get(clientController.handleGetMachines)
router.route('/mining/buy/:id')
    .post(clientController.handleBuyMachine)
router.route('/mining/start/:id')
    .post(clientController.handleStartMachine)
router.route('/mining/stop/:id')
    .post(clientController.handleStopMachine)
router.route('/:id')
    .get(clientController.getClientHandler)
    .delete(clientController.deleteClientHandler)

module.exports = router