import { Link } from 'react-router-dom'
import { motion } from 'framer-motion'
import {
  TrendingUp, Security, Speed, Analytics, Memory,
  AccountBalanceWallet, SignalCellularAlt, SwapHoriz,
  CheckCircleRounded, ArrowForward, SupportAgent,
  BarChart, Shield, Bolt
} from '@mui/icons-material'

const fadeUp = (delay = 0) => ({
  initial: { opacity: 0, y: 28 },
  whileInView: { opacity: 1, y: 0 },
  viewport: { once: true },
  transition: { duration: 0.65, delay },
})

const services = [
  {
    icon: TrendingUp,
    title: 'Investment Plans',
    tag: 'Core',
    body: 'Choose from Basic, Standard, or Golden tiers — each engineered with zero spreads, competitive leverage, and no overnight swap charges. Your capital works harder from day one.',
    features: ['Zero commission trading', 'Up to unlimited leverage', 'No overnight swap fees', 'Minimum 0.01 lot trades'],
    accent: 'from-primary-500 to-primary-700',
    bg: 'bg-primary-50 dark:bg-primary-900/20',
    color: 'text-primary-600 dark:text-primary-400',
  },
  {
    icon: SignalCellularAlt,
    title: 'AI Trading Signals',
    tag: 'Popular',
    body: 'Receive institutional-grade buy and sell signals generated by our proprietary AI engine. Signals cover crypto, forex, and commodities — delivered in real time to your dashboard.',
    features: ['Real-time signal delivery', 'Crypto & forex coverage', 'Risk-rated recommendations', 'Historical performance data'],
    accent: 'from-emerald-500 to-teal-600',
    bg: 'bg-emerald-50 dark:bg-emerald-900/20',
    color: 'text-emerald-600 dark:text-emerald-400',
    featured: true,
  },
  {
    icon: Memory,
    title: 'Cloud Mining',
    tag: 'New',
    body: 'Rent access to physical ASIC and GPU mining rigs running 24/7 in our data centres. Earnings accumulate in your dedicated Mining Account with zero hardware overhead.',
    features: ['Multiple machine tiers', 'Instant activation', 'Live earnings dashboard', 'Withdraw anytime'],
    accent: 'from-violet-500 to-purple-700',
    bg: 'bg-violet-50 dark:bg-violet-900/20',
    color: 'text-violet-600 dark:text-violet-400',
  },
  {
    icon: AccountBalanceWallet,
    title: 'Multi-Account Wallet',
    tag: 'Infrastructure',
    body: 'Manage Funding, Trading, and Mining balances from a single dashboard. Transfer between accounts, track every transaction, and withdraw to any saved wallet or bank account.',
    features: ['3 segregated accounts', 'Instant internal transfers', 'Full transaction history', 'Multiple withdrawal methods'],
    accent: 'from-blue-500 to-primary-700',
    bg: 'bg-blue-50 dark:bg-blue-900/20',
    color: 'text-blue-600 dark:text-blue-400',
  },
  {
    icon: BarChart,
    title: 'Portfolio Analytics',
    tag: 'Insights',
    body: 'Track your performance across all accounts with detailed charts, P&L breakdowns, and trade history. Make data-driven decisions with the same analytics tools used by professionals.',
    features: ['Real-time P&L tracking', 'Trade activity logs', 'Investment performance charts', 'Exportable reports'],
    accent: 'from-amber-500 to-orange-600',
    bg: 'bg-amber-50 dark:bg-amber-900/20',
    color: 'text-amber-600 dark:text-amber-400',
  },
  {
    icon: SupportAgent,
    title: '24 / 7 Client Support',
    tag: 'Support',
    body: 'Our dedicated support team is available around the clock via live chat, email, and in-app messaging. Every query is handled by a trained financial services professional.',
    features: ['24/7 live chat support', 'In-app messaging system', 'Dedicated account managers', 'Multi-language support'],
    accent: 'from-rose-500 to-red-600',
    bg: 'bg-rose-50 dark:bg-rose-900/20',
    color: 'text-rose-600 dark:text-rose-400',
  },
]

const pillars = [
  { icon: Bolt,     title: 'Speed',     body: 'Sub-millisecond order execution routed through our proprietary engine across 30+ global venues.' },
  { icon: Shield,   title: 'Security',  body: 'Cold-storage custody, end-to-end encryption, and real-time fraud detection on every account.' },
  { icon: Analytics,title: 'Analytics', body: 'AI-powered market intelligence and live signals give you the edge professionals rely on daily.' },
  { icon: SwapHoriz,title: 'Liquidity', body: 'Deep liquidity pools ensure your orders fill at the price you see — no slippage, no surprises.' },
]

const process = [
  { step: '01', title: 'Create Your Account',   body: 'Sign up in under 5 minutes. Complete KYC verification to unlock full platform access.' },
  { step: '02', title: 'Fund Your Account',      body: 'Deposit via crypto or bank transfer. Funds are credited instantly to your Funding Account.' },
  { step: '03', title: 'Choose Your Service',    body: 'Select an investment plan, activate a mining machine, or follow AI signals — or all three.' },
  { step: '04', title: 'Track & Withdraw',       body: 'Monitor performance in real time and withdraw your earnings to any saved account at any time.' },
]

const Service = () => (
  <div className="bg-white dark:bg-darkBg pt-20">

    {/* ── Breadcrumb ── */}
    <div className="max-w-7xl mx-auto px-6 md:px-12 py-6">
      <nav className="flex items-center gap-2 text-sm">
        <Link to="/" className="text-primary-600 dark:text-primary-400 hover:underline font-medium">Home</Link>
        <span className="text-neutral-400">/</span>
        <span className="text-neutral-600 dark:text-neutral-300 font-medium">Services</span>
      </nav>
    </div>

    {/* ══════════════════════════════════════════════
        SECTION 1 — Hero
    ══════════════════════════════════════════════ */}
    <div className="relative overflow-hidden bg-gradient-to-br from-neutral-900 via-primary-950 to-neutral-900 py-28 px-6">
      <div className="absolute top-0 left-1/3 w-[500px] h-[500px] rounded-full bg-primary-600/10 blur-3xl pointer-events-none" />
      <div className="absolute bottom-0 right-1/4 w-80 h-80 rounded-full bg-violet-600/10 blur-3xl pointer-events-none" />

      <motion.div {...fadeUp()} className="relative z-10 max-w-4xl mx-auto text-center">
        <span className="inline-block mb-5 px-4 py-1.5 rounded-full bg-primary-500/20 border border-primary-500/30 text-primary-300 font-display font-semibold text-sm tracking-wide">
          What We Offer
        </span>
        <h1 className="mb-6 text-4xl md:text-6xl font-bold font-display text-white leading-tight">
          One Platform.{' '}
          <span className="text-primary-400">Every Financial Tool You Need.</span>
        </h1>
        <p className="max-w-2xl mx-auto font-sans text-lg text-neutral-300 leading-relaxed mb-10">
          From AI-powered trading signals and managed investment plans to cloud mining and multi-account portfolio management — Stock Exchange Mining brings institutional-grade finance to every investor.
        </p>
        <div className="flex flex-col sm:flex-row items-center justify-center gap-4">
          <Link to="/register" className="font-display inline-flex items-center gap-2 bg-primary-600 hover:bg-primary-700 text-white font-semibold px-8 py-3.5 rounded-lg transition-colors duration-200">
            Get Started Free <ArrowForward fontSize="small" />
          </Link>
          <Link to="/auth/user/login" className="font-display inline-flex items-center gap-2 border border-white/30 hover:border-white text-white hover:bg-white/10 font-medium px-8 py-3.5 rounded-lg transition-colors duration-200">
            Login to Dashboard
          </Link>
        </div>
      </motion.div>
    </div>

    {/* ══════════════════════════════════════════════
        SECTION 2 — Platform Pillars
    ══════════════════════════════════════════════ */}
    <div className="bg-primary-600 dark:bg-primary-700">
      <div className="max-w-7xl mx-auto px-6 md:px-12 py-10 grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
        {pillars.map((p, i) => {
          const Icon = p.icon
          return (
            <motion.div key={i} {...fadeUp(i * 0.08)} className="flex items-start gap-4">
              <div className="w-10 h-10 rounded-lg bg-white/20 flex items-center justify-center flex-shrink-0">
                <Icon className="text-white" fontSize="small" />
              </div>
              <div>
                <p className="font-display font-bold text-white text-sm">{p.title}</p>
                <p className="font-sans text-xs text-primary-200 mt-0.5 leading-relaxed">{p.body}</p>
              </div>
            </motion.div>
          )
        })}
      </div>
    </div>

    {/* ══════════════════════════════════════════════
        SECTION 3 — Service Cards
    ══════════════════════════════════════════════ */}
    <div className="max-w-7xl mx-auto px-6 md:px-12 py-24">
      <motion.div {...fadeUp()} className="text-center mb-16">
        <span className="inline-block mb-4 px-4 py-1.5 rounded-full bg-primary-50 dark:bg-primary-900/30 text-primary-600 dark:text-primary-400 font-display font-semibold text-sm tracking-wide">
          Our Services
        </span>
        <h2 className="text-3xl md:text-4xl font-bold font-display text-neutral-900 dark:text-white mb-4">
          Everything Under{' '}
          <span className="text-primary-600 dark:text-primary-400">One Roof</span>
        </h2>
        <p className="max-w-xl mx-auto font-sans text-base text-neutral-600 dark:text-neutral-400">
          Six fully integrated services designed to work together and grow with your financial goals.
        </p>
      </motion.div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {services.map((s, i) => {
          const Icon = s.icon
          return (
            <motion.div key={i} {...fadeUp(i * 0.08)}
              className={`relative flex flex-col bg-white dark:bg-neutral-800 border rounded-2xl overflow-hidden shadow-soft hover:shadow-medium hover:-translate-y-1 transition-all duration-300 ${
                s.featured ? 'border-primary-400 dark:border-primary-500' : 'border-neutral-200 dark:border-neutral-700'
              }`}>
              {/* Top accent */}
              <div className={`h-1 w-full bg-gradient-to-r ${s.accent}`} />

              {s.featured && (
                <div className="absolute top-4 right-4 px-2.5 py-0.5 rounded-full bg-primary-600 text-white text-xs font-bold font-display">
                  Most Popular
                </div>
              )}

              <div className="p-6 flex flex-col flex-1">
                <div className="flex items-start gap-4 mb-4">
                  <div className={`w-11 h-11 rounded-xl flex items-center justify-center flex-shrink-0 ${s.bg}`}>
                    <Icon className={s.color} />
                  </div>
                  <div>
                    <span className="text-xs font-semibold font-display text-neutral-400 uppercase tracking-wide">{s.tag}</span>
                    <h3 className="font-display font-bold text-neutral-900 dark:text-white">{s.title}</h3>
                  </div>
                </div>

                <p className="font-sans text-sm leading-relaxed text-neutral-600 dark:text-neutral-400 mb-5">{s.body}</p>

                <ul className="space-y-2 mt-auto">
                  {s.features.map((f, j) => (
                    <li key={j} className="flex items-center gap-2">
                      <CheckCircleRounded className={s.color} style={{ fontSize: 16 }} />
                      <span className="font-sans text-xs text-neutral-700 dark:text-neutral-300">{f}</span>
                    </li>
                  ))}
                </ul>
              </div>
            </motion.div>
          )
        })}
      </div>
    </div>

    {/* ══════════════════════════════════════════════
        SECTION 4 — How It Works
    ══════════════════════════════════════════════ */}
    <div className="bg-neutral-50 dark:bg-neutral-900 border-y border-neutral-200 dark:border-neutral-800">
      <div className="max-w-7xl mx-auto px-6 md:px-12 py-24">
        <motion.div {...fadeUp()} className="text-center mb-16">
          <span className="inline-block mb-4 px-4 py-1.5 rounded-full bg-primary-50 dark:bg-primary-900/30 text-primary-600 dark:text-primary-400 font-display font-semibold text-sm tracking-wide">
            How It Works
          </span>
          <h2 className="text-3xl md:text-4xl font-bold font-display text-neutral-900 dark:text-white mb-4">
            Up and Running in{' '}
            <span className="text-primary-600 dark:text-primary-400">Four Steps</span>
          </h2>
          <p className="max-w-xl mx-auto font-sans text-base text-neutral-600 dark:text-neutral-400">
            No complexity, no waiting. From sign-up to first earnings in minutes.
          </p>
        </motion.div>

        <div className="relative grid grid-cols-1 md:grid-cols-4 gap-8">
          {/* Connector — desktop */}
          <div className="hidden md:block absolute top-10 left-[calc(12.5%+1rem)] right-[calc(12.5%+1rem)] h-px bg-neutral-200 dark:bg-neutral-700 z-0" />

          {process.map((p, i) => (
            <motion.div key={i} {...fadeUp(i * 0.1)} className="relative z-10 flex flex-col items-center text-center">
              <div className="w-20 h-20 rounded-full bg-gradient-to-br from-primary-500 to-primary-700 flex items-center justify-center mb-5 shadow-medium">
                <span className="font-display font-bold text-white text-lg">{p.step}</span>
              </div>
              <h3 className="mb-2 font-display font-bold text-neutral-900 dark:text-white">{p.title}</h3>
              <p className="font-sans text-sm leading-relaxed text-neutral-600 dark:text-neutral-400 max-w-[200px]">{p.body}</p>
            </motion.div>
          ))}
        </div>

        <motion.div {...fadeUp(0.4)} className="flex justify-center mt-14">
          <Link to="/register" className="font-display inline-flex items-center gap-2 bg-primary-600 hover:bg-primary-700 text-white font-semibold px-10 py-4 rounded-lg transition-colors duration-200">
            Start Now — It's Free <ArrowForward fontSize="small" />
          </Link>
        </motion.div>
      </div>
    </div>

    {/* ══════════════════════════════════════════════
        SECTION 5 — CTA
    ══════════════════════════════════════════════ */}
    <div className="bg-gradient-to-br from-primary-600 to-primary-900 py-20 px-6">
      <motion.div {...fadeUp()} className="max-w-3xl mx-auto text-center">
        <div className="w-14 h-14 rounded-2xl bg-white/20 flex items-center justify-center mx-auto mb-6">
          <Security className="text-white" fontSize="large" />
        </div>
        <h2 className="mb-4 text-3xl md:text-4xl font-bold font-display text-white leading-snug">
          Ready to Access Institutional-Grade Markets?
        </h2>
        <p className="mb-8 font-sans text-lg text-primary-200 max-w-xl mx-auto">
          Join thousands of traders who execute with precision, speed, and confidence every single day.
        </p>
        <div className="flex flex-col sm:flex-row items-center justify-center gap-4">
          <Link to="/register" className="font-display inline-flex items-center gap-2 bg-white text-primary-700 hover:bg-primary-50 font-semibold px-8 py-3.5 rounded-lg transition-colors duration-200">
            Create Free Account <ArrowForward fontSize="small" />
          </Link>
          <Link to="/auth/user/login" className="font-display inline-flex items-center gap-2 border border-white/40 hover:border-white text-white hover:bg-white/10 font-medium px-8 py-3.5 rounded-lg transition-colors duration-200">
            Login to Dashboard
          </Link>
        </div>
      </motion.div>
    </div>

  </div>
)

export default Service
