const notifications = [
  { id: 1, title: "Crypto Profit", name: "Marcus", location: "Singapore", amount: "$45,230", message: "earned from Bitcoin trading" },
  { id: 2, title: "Forex Trade", name: "Sarah", location: "London", amount: "$12,500", message: "profited from EUR/USD scalping" },
  { id: 3, title: "DeFi Yield", name: "David", location: "Seoul", amount: "$8,750", message: "earned from smart contract staking" },
  { id: 4, title: "Arbitrage", name: "Elena", location: "Moscow", amount: "$3,400", message: "profited from cross-exchange trading" },
  { id: 5, title: "AI Trading", name: "James", location: "New York", amount: "$28,900", message: "earned from automated strategies" },
  { id: 6, title: "Crypto Mining", name: "Priya", location: "Mumbai", amount: "$6,800", message: "earned from mining rewards" },
  { id: 7, title: "NFT Trade", name: "Alex", location: "Toronto", amount: "$15,600", message: "profited from NFT trading" },
  { id: 8, title: "Options", name: "Maria", location: "São Paulo", amount: "$22,100", message: "earned from Bitcoin options" },
  { id: 9, title: "Swing Trade", name: "Robert", location: "Sydney", amount: "$9,450", message: "profited from altcoin swing" },
  { id: 10, title: "Forex Signal", name: "Isabella", location: "Madrid", amount: "$7,200", message: "earned from GBP/JPY signals" },
  { id: 11, title: "Crypto Bot", name: "Thomas", location: "Berlin", amount: "$18,300", message: "earned from trading bots" },
  { id: 12, title: "DeFi Pool", name: "Chen", location: "Shanghai", amount: "$11,900", message: "earned from liquidity mining" },
  { id: 13, title: "Scalping", name: "Ahmed", location: "Dubai", amount: "$5,670", message: "profited from crypto scalping" },
  { id: 14, title: "Yield Farm", name: "Sophie", location: "Paris", amount: "$13,400", message: "earned from yield farming" },
  { id: 15, title: "Forex Bot", name: "Lucas", location: "Amsterdam", amount: "$8,900", message: "profited from forex automation" },
  { id: 16, title: "Crypto Stake", name: "Yuki", location: "Tokyo", amount: "$16,750", message: "earned from proof-of-stake rewards" },
  { id: 17, title: "AI Signal", name: "Emma", location: "Stockholm", amount: "$4,320", message: "profited from AI predictions" },
  { id: 18, title: "Cross Trade", name: "Omar", location: "Cairo", amount: "$12,800", message: "earned from cross-pair trading" },
  { id: 19, title: "DeFi Swap", name: "Fatima", location: "Karachi", amount: "$6,150", message: "profited from token swaps" },
  { id: 20, title: "Futures", name: "Liam", location: "Dublin", amount: "$25,600", message: "earned from crypto futures" },
  { id: 21, title: "Grid Bot", name: "Anna", location: "Helsinki", amount: "$9,800", message: "profited from grid trading" },
  { id: 22, title: "Forex Carry", name: "Miguel", location: "Mexico City", amount: "$7,450", message: "earned from carry trades" },
  { id: 23, title: "Crypto Loan", name: "Zara", location: "Riyadh", amount: "$14,200", message: "earned from lending rewards" },
  { id: 24, title: "Algo Trade", name: "Noah", location: "Vancouver", amount: "$19,500", message: "profited from algorithms" },
  { id: 25, title: "Flash Loan", name: "Aisha", location: "Lagos", amount: "$3,800", message: "earned from flash arbitrage" },
  { id: 26, title: "Perpetual", name: "Dmitry", location: "Kiev", amount: "$11,300", message: "profited from perpetual swaps" },
  { id: 27, title: "Margin Trade", name: "Sakura", location: "Osaka", amount: "$8,650", message: "earned from margin trading" },
  { id: 28, title: "Copy Trade", name: "Hassan", location: "Casablanca", amount: "$5,900", message: "profited from copy trading" },
  { id: 29, title: "Spot Trade", name: "Eva", location: "Copenhagen", amount: "$12,400", message: "earned from spot trading" },
  { id: 30, title: "Hedge Fund", name: "Carlos", location: "Buenos Aires", amount: "$31,700", message: "profited from hedge strategies" },
  { id: 31, title: "Crypto Index", name: "Lily", location: "Wellington", amount: "$7,800", message: "earned from index trading" },
  { id: 32, title: "Forex Hedge", name: "Ali", location: "Kuala Lumpur", amount: "$9,200", message: "profited from hedging" },
  { id: 33, title: "DeFi Vault", name: "Nora", location: "Oslo", amount: "$15,100", message: "earned from vault strategies" },
  { id: 34, title: "Swing Bot", name: "Gabriel", location: "Rio de Janeiro", amount: "$6,750", message: "profited from swing bots" },
  { id: 35, title: "Trend Follow", name: "Elif", location: "Istanbul", amount: "$10,900", message: "earned from trend following" },
  { id: 36, title: "Mean Revert", name: "Khalid", location: "Amman", amount: "$4,600", message: "profited from mean reversion" },
  { id: 37, title: "Momentum", name: "Fatou", location: "Dakar", amount: "$8,300", message: "earned from momentum trading" },
  { id: 38, title: "Breakout", name: "Isak", location: "Reykjavik", amount: "$13,800", message: "profited from breakout trades" },
  { id: 39, title: "Range Trade", name: "Amina", location: "Tunis", amount: "$5,400", message: "earned from range trading" },
  { id: 40, title: "News Trade", name: "Nikolai", location: "Almaty", amount: "$17,200", message: "profited from news trading" },
  { id: 41, title: "Social Trade", name: "Anastasia", location: "Minsk", amount: "$7,650", message: "earned from social signals" },
  { id: 42, title: "Whale Alert", name: "Tomás", location: "Lisbon", amount: "$21,400", message: "profited from whale movements" },
  { id: 43, title: "Flash Trade", name: "Zahra", location: "Tehran", amount: "$9,100", message: "earned from flash trading" },
  { id: 44, title: "Micro Trade", name: "Johan", location: "Brussels", amount: "$3,250", message: "profited from micro trades" },
  { id: 45, title: "Macro Trade", name: "Sofia", location: "Athens", amount: "$26,800", message: "earned from macro strategies" },
  { id: 46, title: "Quant Model", name: "Mikhail", location: "St. Petersburg", amount: "$18,900", message: "profited from quant models" },
  { id: 47, title: "Risk Parity", name: "Jasmine", location: "Auckland", amount: "$14,500", message: "earned from risk parity" },
  { id: 48, title: "Vol Trading", name: "Emir", location: "Ankara", amount: "$11,700", message: "profited from volatility trading" },
  { id: 49, title: "Pairs Trade", name: "Anika", location: "Dhaka", amount: "$6,900", message: "earned from pairs trading" },
  { id: 50, title: "Stat Arb", name: "Ismail", location: "Algiers", amount: "$22,300", message: "profited from statistical arbitrage" }
];

export default notifications;